package com.dobby.enums

enum class University(
    val displayName: String
) {
    CATHOLIC_UNIV("가톨릭대학교"),
    KANGSEO_UNIV("강서대학교"),
    KONKUK_UNIV("건국대학교"),
    KYEONGGI_UNIV("경기대학교"),
    KYEONGHI_UNIV("경희대학교"),
    KOREA_UNIV("고려대학교"),
    KWANGWOON_UNIV("광운대학교"),
    KOOKMIN_UNIV("국민대학교"),
    DONGGUK_UNIV("동국대학교"),
    MYEONGJI_UNIV("명지대학교"),
    SAMYOOK_UNIV("삼육대학교"),
    SANGMYEONG_UNIV("상명대학교"),
    SOGANG_UNIV("서강대학교"),
    SEOGYEONG_UNIV("서경대학교"),
    SEOUL_TECH_UNIV("서울과학기술대학교"),
    SEOUL_NATIONAL_UNIV("서울대학교"),
    SEOUL_UNIV("서울시립대학교"),
    SEOUL_HANYEONG_UNIV("서울한영대학교"),
    SUNGKONGHOE_UNIV("성공회대학교"),
    SUNGKYUNKWAN_UNIV("성균관대학교"),
    SEJOING_UNIV("세종대학교"),
    SOONGSIL_UNIV("숭실대학교"),
    YEONSEI_UNIV("연세대학교"),
    CHUNGANG_UNIV("중앙대학교"),
    CHONGSIN_UNIV("총신대학교"),
    CHUGYE_ART_UNIV("추계예술대학교"),
    HANKUK_FOREIGN_UNIV("한국외국어대학교"),
    KOREA_NATIONAL_SPORT_UNIV("한국체육대학교"),
    HANSUNG_UNIV("한성대학교"),
    HANYANG_UNIV("한양대학교"),
    HONGIK_UNIV("홍익대학교"),
    SEOUL_EDU_UNIV("서울교육대학교"),
    DUKSUNG_WOMEN_UNIV("덕성여자대학교"),
    DONGDUK_WOMEN_UNIV("동덕여자대학교"),
    SEOUL_WOMEN_UNIV("서울여자대학교"),
    SUNGSHIN_WOMEN_UNIV("성신여자대학교"),
    SOOKMYUNG_WOMEN_UNIV("숙명여자대학교"),
    EWHA_WOMANS_UNIV("이화여자대학교"),
    METHODIST_UNIV("감리교신학대학교"),
    SEOUL_CHRISTIAN_UNIV("서울기독대학교"),
    PRESBYTERIAN_UNIV("장로회신대학교"),
    KOREAN_BIBLE_UNIV("한국성서대학교"),

    GACHEON_UNIV("가천대학교"),
    GANGNAM_UNIV("강남대학교"),
    GYEONGDONG_UNIV("경동대학교"),
    GYEONGIN_EDU_UNIV("경인교육대학교"),
    KOREA_TRANSPORTATION_UNIV("국립한국교통대학교"),
    DANGUK_UNIV("단국대학교"),
    DAEJIN_UNIV("대진대학교"),
    DONGYANG_UNIV("동양대학교"),
    RUTER_UNIV("루터대학교"),
    SEONGGYEOL_UNIV("성결대학교"),
    SUWON_UNIV("수원대학교"),
    HWASUNG_MEDI_UNIV("화성의과학대학교"),
    SHINHAN_UNIV("신한대학교"),
    AJOU_UNIV("아주대학교"),
    ANYANG_UNIV("안양대학교"),
    YEWON_ARTS_UNIV("예원예술대학교"),
    YONGIN_UNIV("용인대학교"),
    EULJI_UNIV("을지대학교"),
    JOONGBU_UNIV("중부대학교"),
    CHUNGANG_DAVINCI_UNIV("중앙대학교 다빈치캠퍼스"),
    CHA_MEDICAL_UNIV("차의과학대학교"),
    PYEONGTAEK_UNIV("평택대학교"),
    HANKYUNG_NATIONAL_UNIV("한경국립대학교"),
    KOREA_POLYTECH_UNIV("한국공학대학교"),
    HANKUK_UNIV_FOREIGN_STUDIES("한국외국어대학교 글로벌캠퍼스"),
    KOREA_AEROSPACE_UNIV("한국항공대학교"),
    HANSEI_UNIV("한세대학교"),
    HANSIN_UNIV("한신대학교"),
    HANYANG_ERICA_UNIV("한양대학교 ERICA캠퍼스"),
    HYUPSUNG_UNIV("협성대학교"),
    CALVIN_UNIV("칼빈대학교"),
    GYEONGIN_EDU_UNIV_INCHEON("경인교육대학교 인천캠퍼스"),
    ANYANG_UNIV_GANGHWA("안양대학교 강화캠퍼스"),
    YONSEI_UNIV_INTL("연세대학교 국제캠퍼스"),
    INCHEON_CATHOLIC_UNIV("인천가톨릭대학교"),
    INCHEON_UNIV("인천대학교"),
    INHA_UNIV("인하대학교"),
    CHUNGWOON_UNIV_INCHEON("청운대학교 인천캠퍼스"),
    SEOUL_JANGSHIN_UNIV("서울장신대학교"),
    SUWON_CATHOLIC_UNIV("수원가톨릭대학교"),
    ASIN_UNIV("아신대학교"),
    JUNGANG_SUNGGA_UNIV("중앙승가대학교"),

    CATHOLIC_KWANDONG_UNIV("가톨릭관동대학교"),
    GANGNEUNG_WONJU_UNIV_GANGNEUNG("강릉원주대학교 강릉캠퍼스"),
    GANGNEUNG_WONJU_UNIV_WONJU("강릉원주대학교 원주캠퍼스"),
    KANGWON_UNIV_CHUNCHEON("강원대학교 춘천캠퍼스"),
    KANGWON_UNIV_SAMCHEOK("강원대학교 삼척캠퍼스"),
    KANGWON_UNIV_DOGYE("강원대학교 도계캠퍼스"),
    GYEONGDONG_GLOBAL_UNIV("경동대학교 글로벌캠퍼스"),
    GYEONGDONG_MEDICAL_UNIV("경동대학교 메디컬캠퍼스"),
    SANGJI_UNIV("상지대학교"),
    YONSEI_MIRAE_UNIV("연세대학교 미래캠퍼스"),
    CHUNCHEON_EDU_UNIV("춘천교육대학교"),
    HALLA_UNIV("한라대학교"),
    HALLYM_UNIV("한림대학교"),

    HANBAT_NATIONAL_UNIV("국립한밭대학교"),
    CHUNGNAM_UNIV("충남대학교"),
    KONYANG_UNIV("건양대학교"),
    DAEJEON_UNIV("대전대학교"),
    DAEJEON_THEO_UNIV("대전신학대학교"),
    MOKWON_UNIV("목원대학교"),
    PAI_CHAI_UNIV("배재대학교"),
    WOOSONG_UNIV("우송대학교"),
    EULJI_UNIV_DAEJEON("을지대학교 대전캠퍼스"),
    KOREA_BAPTIST_THEO_UNIV("한국침례신학대학교"),
    HANNAM_UNIV("한남대학교"),

    KAIST("한국과학기술원"),

    KOREAN_NATIONAL_POLICE_UNIV("경찰대학"),
    GONGJU_EDU_UNIV("공주교육대학교"),
    KONGJU_NATIONAL_UNIV("국립공주대학교"),
    KOREA_NATIONAL_UNIV_CULTURAL_HERITAGE("한국전통문화대학교"),
    KOSHIN_UNIV_CHEONAN("고신대학교 천안캠퍼스"),
    GEUMGANG_UNIV("금강대학교"),
    NAGASAKI_UNIV("나사렛대학교"),
    NAMSEOUL_UNIV("남서울대학교"),
    DANKOOK_UNIV_CHEONAN("단국대학교 천안캠퍼스"),
    BAEKSEOK_UNIV("백석대학교"),
    SANGMYUNG_UNIV_CHEONAN("상명대학교 천안캠퍼스"),
    SUNMOON_UNIV("선문대학교"),
    SEHAN_UNIV("세한대학교"),
    SOONCHUNHYANG_UNIV("순천향대학교"),
    U1_UNIV("유원대학교 아산캠퍼스"),
    CHUNGWOON_UNIV_CHEONG("청운대학교 홍성캠퍼스"),
    KOREA_TECH_UNIV("한국기술교육대학교"),
    HANSUH_UNIV("한서대학교"),
    HOSEO_UNIV("호서대학교"),

    KOREA_UNIV_SEJONG("고려대학교 세종캠퍼스"),
    CATHOLIC_UNIV_DAEJEON("대전가톨릭대학교"),
    HONGIK_UNIV_SEJONG("홍익대학교 세종캠퍼스"),
    KUNKUK_UNIV_GLOCAL("건국대학교 글로컬캠퍼스"),
    KUKDONG_UNIV("극동대학교"),
    CATHOLIC_KKOTDONGNE_UNIV("가톨릭꽃동네대학교"),
    SEOWON_UNIV("서원대학교"),
    SEMYUNG_UNIV("세명대학교"),
    U1_UNIV_YEONGDONG("유원대학교 영동캠퍼스"),
    WOOSUK_UNIV_JINCHEON("우석대학교 진천캠퍼스"),
    JOONGWON_UNIV("중원대학교"),
    CHEONGJU_UNIV("청주대학교"),
    CHUNGBUK_NATIONAL_UNIV("충북대학교"),
    CHEONGJU_EDU_UNIV("청주교육대학교"),
    KOREA_NATIONAL_UNIV_OF_EDUCATION("한국교원대학교"),
    KOREA_TRANSPORTATION_UNIV_CHUNGJU("국립한국교통대학교 충주캠퍼스"),
    KOREA_TRANSPORTATION_UNIV_JEUNGPYEONG("국립한국교통대학교 증평캠퍼스"),

    AIR_FORCE_ACADEMY("공군사관학교"),
    KOREAN_NATIONAL_DEFENSE_NURSING_ACADEMY("국군간호사관학교"),

    DGIST("대구경북과학기술원"),
    DAEGU_EDU_UNIV("대구교육대학교"),
    KYUNGPOOK_NATIONAL_UNIV("경북대학교"),
    KYEMYUNG_UNIV("계명대학교"),
    DAEGU_CATHOLIC_UNIV("대구가톨릭대학교"),
    DAEGU_UNIV("대구대학교"),
    DAEGU_HANUI_UNIV("대구한의대학교"),

    KYUNGPOOK_NATIONAL_UNIV_SANGJU("경북대학교 상주캠퍼스"),
    KYUNGWOON_UNIV("경운대학교"),
    KYUNGIL_UNIV("경일대학교"),
    GYEONGJU_UNIV("경주대학교"),
    KUMOH_NATIONAL_INST_TECH("금오공과대학교"),
    KIMCHEON_UNIV("김천대학교"),
    DAEGU_CATHOLIC_UNIV_HYOSEONG("대구가톨릭대학교 효성캠퍼스"),
    DAEGU_UNIV_GYUNGSAN("대구대학교 경산캠퍼스"),
    DAEGU_ART_UNIV("대구예술대학교"),
    DAEGU_HANUI_UNIV_SAMSUNG("대구한의대학교 삼성캠퍼스"),
    DAEGU_HANUI_UNIV_OSEONG("대구한의대학교 오성캠퍼스"),
    DAESHIN_UNIV("대신대학교"),
    DONGGUK_WISE_UNIV("동국대학교 Wise캠퍼스"),
    DONGYANG_UNIV_YEONGJU("동양대학교 영주캠퍼스"),
    ANDONG_NATIONAL_UNIV("국립안동대학교"),
    KMA_THIRD_ACADEMY("육군3사관학교"),
    YOUNGNAM_UNIV("영남대학교"),
    YOUNGNAM_THEO_UNIV("영남신학대학교"),
    WIDUK_UNIV("위덕대학교"),
    POSTECH("포항공과대학교"),
    HANDONG_GLOBAL_UNIV("한동대학교"),

    KAYA_UNIV("가야대학교"),
    KYUNGNAM_UNIV_WOLYEONG("경남대학교 월영캠퍼스"),
    KYUNGNAM_UNIV_PARYONG("경남대학교 팔용캠퍼스"),
    GYEONGSANG_NATIONAL_UNIV_GAJA("경상국립대학교 가좌캠퍼스"),
    GYEONGSANG_NATIONAL_UNIV_NAEDONG("경상국립대학교 내동캠퍼스"),
    GYEONGSANG_NATIONAL_UNIV_CHIRAM("경상국립대학교 칠암캠퍼스"),
    GYEONGSANG_NATIONAL_UNIV_TONGYEONG("경상국립대학교 통영캠퍼스"),
    GYEONGSANG_NATIONAL_UNIV_CHANGWON("경상국립대학교 창원캠퍼스"),
    CHANGWON_NATIONAL_UNIV("국립창원대학교"),
    PNU_YANGSAN("부산대학교 양산캠퍼스"),
    PNU_MIRYANG("부산대학교 밀양캠퍼스"),
    BUSAN_JANGSHIN_UNIV("부산장신대학교"),
    YOUNGSAN_UNIV_YANGSAN("영산대학교 양산캠퍼스"),
    INJE_UNIV_GIMHAE("인제대학교 김해캠퍼스"),
    JINJU_EDU_UNIV("진주교육대학교"),
    CHANGSHIN_UNIV("창신대학교"),
    KOREAN_NAVAL_ACADEMY("해군사관학교"),

    KYUNGSUNG_UNIV("경성대학교"),
    KOSHIN_UNIV_YEONGDO("고신대학교 영도캠퍼스"),
    KOSHIN_UNIV_SONGDO("고신대학교 송도캠퍼스"),
    PUKYONG_NATIONAL_UNIV("국립부경대학교"),
    KOREA_MARITIME_UNIV("국립한국해양대학교"),
    DONGMYUNG_UNIV("동명대학교"),
    DONGBU_UNIV("동서대학교"),
    DONGA_UNIV_SEUNGHAG("동아대학교 승학캠퍼스"),
    DONGA_UNIV_BUMIN("동아대학교 부민캠퍼스"),
    DONGA_UNIV_GUDEOK("동아대학교 구덕캠퍼스"),
    DONGEUI_UNIV_GAYA("동의대학교 가야캠퍼스"),
    DONGEUI_UNIV_YANGJEONG("동의대학교 양정캠퍼스"),
    BUSAN_CATHOLIC_UNIV("부산가톨릭대학교"),
    BUSAN_EDU_UNIV("부산교육대학교"),
    PNU_BUSAN("부산대학교 부산캠퍼스"),
    BUSAN_UNIV_FOREIGN_STUDIES("부산외국어대학교"),
    SILLA_UNIV("신라대학교"),
    YOUNGSAN_UNIV_HAEUNDAE("영산대학교 해운대캠퍼스"),
    INJE_UNIV_BUSAN("인제대학교 부산캠퍼스"),

    UNIST("울산과학기술원"),

    GIST("광주과학기술원"),
    GWANGJU_EDU_UNIV("광주교육대학교"),
    CHONNAM_UNIV_YONGBONG("전남대학교 용봉캠퍼스"),
    CHONNAM_UNIV_HAKDONG("전남대학교 학동캠퍼스"),
    GWANGSHIN_UNIV("광신대학교"),
    GWANGJU_UNIV("광주대학교"),
    GWANGJU_WOMENS_UNIV("광주여자대학교"),
    NAMBU_UNIV("남부대학교"),
    SONGWON_UNIV("송원대학교"),
    CHOSUN_UNIV("조선대학교"),
    HONAM_UNIV("호남대학교"),
    HONAM_THEO_UNIV("호남신학대학교"),

    MOKPO_NATIONAL_UNIV_DORIM("국립목포대학교 도림캠퍼스"),
    MOKPO_NATIONAL_UNIV_NAMAK("국립목포대학교 남악캠퍼스"),
    MOKPO_NATIONAL_UNIV_MOKPO("국립목포대학교 목포캠퍼스"),
    MOKPO_NATIONAL_UNIV_DAEBUL("국립목포대학교 대불캠퍼스"),
    MOKPO_NATIONAL_UNIV_NAJU("국립목포대학교 나주캠퍼스"),
    MOKPO_MARITIME_UNIV("국립목포해양대학교"),
    SUNCHEON_NATIONAL_UNIV("국립순천대학교"),
    CHONNAM_UNIV_YEOSU("전남대학교 여수캠퍼스"),
    CHONNAM_UNIV_SANHAK("전남대학교 산학융합캠퍼스"),
    KEPCO_INSTITUTE("한국에너지공과대학교"),
    GWANGJU_CATHOLIC_UNIV("광주가톨릭대학교"),
    DONGSHIN_UNIV("동신대학교"),
    MOKPO_CATHOLIC_UNIV("목포가톨릭대학교"),
    SEHAN_UNIV_YEONGAM("세한대학교 영암캠퍼스"),
    YOUNGSAN_SUNHAK_UNIV("영산선학대학교"),
    CHODANG_UNIV("초당대학교"),

    KUNSAN_NATIONAL_UNIV_MIRYONG("국립군산대학교 미룡캠퍼스"),
    KUNSAN_NATIONAL_UNIV_SAEMANGEUM("국립군산대학교 새만금캠퍼스"),
    YESU_UNIV("예수대학교"),
    YEWON_ARTS_UNIV_HOPE("예원예술대학교 희망캠퍼스"),
    WOOSUK_UNIV_JEONJU("우석대학교 전주캠퍼스"),
    WOOSUK_UNIV_WANSAN("우석대학교 완산캠퍼스"),
    WONKWANG_UNIV("원광대학교"),
    CHONBUK_NATIONAL_UNIV_JEONJU("전북대학교 전주캠퍼스"),
    CHONBUK_NATIONAL_UNIV_SPECIALIZED("전북대학교 특성화캠퍼스"),
    CHONBUK_NATIONAL_UNIV_GOCHANG("전북대학교 고창캠퍼스"),
    CHONBUK_NATIONAL_UNIV_SAEMANGEUM("전북대학교 새만금캠퍼스"),
    JEONJU_EDU_UNIV("전주교육대학교"),
    JEONJU_UNIV("전주대학교 전주캠퍼스"),
    HANIL_JANGSHIN_UNIV("한일장신대학교"),
    HOWON_UNIV("호원대학교 군산캠퍼스"),

    JEJU_INTL_UNIV("제주국제대학교"),
    JEJU_NATIONAL_UNIV_ARA("제주대학교 아라캠퍼스"),
    JEJU_NATIONAL_UNIV_SARA("제주대학교 사라캠퍼스")
    ;

    val initial: String by lazy { extractInitial(displayName) }

    companion object {

        fun match(keyword: String): List<String> {
            return entries.filter {
                when {
                    keyword.length == 1 -> it.initial.startsWith(keyword)
                    else -> it.displayName.contains(keyword, ignoreCase = true) || it.initial.contains(keyword)
                }
            }.map { it.displayName }
        }

        /**
         * 초성 검색 기능을 위한 초성 추출 함수
         */
        private fun extractInitial(input: String): String {
            val initialConsonants = listOf(
                'ㄱ', 'ㄲ', 'ㄴ', 'ㄷ', 'ㄸ', 'ㄹ',
                'ㅁ', 'ㅂ', 'ㅃ', 'ㅅ', 'ㅆ', 'ㅇ',
                'ㅈ', 'ㅉ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'
            )

            return input.mapNotNull { ch ->
                if (ch in '가'..'힣') {
                    val index = (ch.code - '가'.code) / 588
                    initialConsonants[index]
                } else {
                    null
                }
            }.joinToString("")
        }
    }
}
