CREATE TABLE IF NOT EXISTS `member` (
    `member_id` CHAR(13) NOT NULL PRIMARY KEY,
    `contact_email` VARCHAR(100) NULL,
    `created_at` DATETIME(6) NOT NULL,
    `name` VARCHAR(10) NULL,
    `oauth_email` VARCHAR(100) NOT NULL UNIQUE,
    `oauth_provider` ENUM ('GOOGLE', 'NAVER') NOT NULL,
    `role` ENUM ('PARTICIPANT', 'RESEARCHER') NULL,
    `status` ENUM ('ACTIVE', 'HOLD') NOT NULL,
    `updated_at` DATETIME(6) NOT NULL,
    `deleted_at` DATETIME(6) NULL
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `member_consent` (
    `member_id` CHAR(13) NOT NULL PRIMARY KEY,
    `ad_consent` BIT NOT NULL,
    `ad_consented_at` DATE NULL,
    `match_consent` BIT NOT NULL,
    `match_consented_at` DATE NULL,
    `created_at` DATETIME(6) NOT NULL,
    `updated_at` DATETIME(6) NOT NULL
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `member_withdrawal` (
    `member_id` CHAR(13) NOT NULL PRIMARY KEY,
    `created_at` DATETIME(6) NOT NULL,
    `other_reason` VARCHAR(255) NULL,
    `reason_type` ENUM ('INCONVENIENT_SITE', 'NO_NECESSARY_FUNCTION', 'OTHER', 'RESEARCH_STOPPED', 'SECURITY_CONCERN', 'TOO_MANY_EMAILS') NOT NULL
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `participant` (
    `participant_id`    CHAR(13) NOT NULL PRIMARY KEY,
    `basic_area`        ENUM ('ANDONGSI', 'ANSAN_DANWONGU', 'ANSAN_SANGROKGU', 'ANSEONGSI', 'ANYANG_DONGANGU', 'ANYANG_MANANGU', 'ASANSI', 'BOEUNGUN', 'BONGHWAGUN', 'BORYEONGSI', 'BOSEONGGUN', 'BUAN', 'BUCHEONSI', 'BUKGU', 'BUPYEONGGU', 'BUSANJINGU', 'BUSAN_ALL', 'BUSAN_DONGGU', 'BUSAN_GANGSEOGU', 'BUSAN_JUNGGU', 'BUSAN_SEOGU', 'BUYEO', 'CHANGWON_JINHAEGU', 'CHANGWON_MASANHAPPOGU', 'CHANGWON_MASANHOEWONGU', 'CHANGWON_SEONGSANGU', 'CHANGWON_UICHANGGU', 'CHANGYEONGGUN', 'CHEONAN_SEOBUKGU', 'CHEONGDOGUN', 'CHEONGJU_CHEONGWONGU', 'CHEONGJU_HEUNGDEOKGU', 'CHEONGJU_SANGDANGGU', 'CHEONGJU_SEOWONGU', 'CHEONGSONGGUN', 'CHEONGYANG', 'CHEORWONGUN', 'CHILGOKGUN', 'CHUNCHEONSI', 'CHUNGBUK_ALL', 'CHUNGJUSI', 'CHUNGNAM_ALL', 'DAEGU_ALL', 'DAEGU_BUKGU', 'DAEGU_DALSEOGU', 'DAEGU_DALSEONGGUN', 'DAEGU_DONGGU', 'DAEGU_JUNGGU', 'DAEGU_NAMGU', 'DAEGU_SEOGU', 'DAEGU_SUSEONGGU', 'DAEJEON_ALL', 'DAEJEON_DAEDOKGU', 'DAEJEON_DONGGU', 'DAEJEON_JUNGGU', 'DAEJEON_SEOGU', 'DAEJEON_YUSEONGGU', 'DAMYANGGUN', 'DANGJINSI', 'DANYANGGUN', 'DOBONGGU', 'DONGDAEMUNGU', 'DONGDUCHEONSI', 'DONGGU', 'DONGHAESI', 'DONGJAKGU', 'DONGNAEGU', 'EUMSEONGGUN', 'EUNPYEONGGU', 'GANGBUKGU', 'GANGDONGGU', 'GANGHWAGUN', 'GANGJINGUN', 'GANGNAMGU', 'GANGNEUNGSI', 'GANGSEOGU', 'GANGWON_ALL', 'GANGWON_GOSEONGGUN', 'GAPYEONGGUN', 'GEOCHANGGUN', 'GEOJESI', 'GEUMCHEONGU', 'GEUMJEONGGU', 'GEUMSANGUN', 'GIJANGGUN', 'GIMCHEONSI', 'GIMHAESI', 'GIMJESI', 'GIMPOSI', 'GOCHANGGUN', 'GOHEUNGGUN', 'GOKSEONGGUN', 'GONGJUSI', 'GORYEONGGUN', 'GOYANG_DEOKYANGGU', 'GOYANG_ILSANDONGGU', 'GOYANG_ILSANSEOGU', 'GUAESANGUN', 'GUMISI', 'GUNPOSI', 'GUNSAN', 'GUNWEEGUN', 'GURISI', 'GUROGU', 'GURYEOGUN', 'GWACHEONSI', 'GWANAKGU', 'GWANGJINGU', 'GWANGJUSI', 'GWANGJU_ALL', 'GWANGJU_BUKGU', 'GWANGJU_DONGGU', 'GWANGJU_GWANGSANGU', 'GWANGJU_NAMGU', 'GWANGJU_SEOGU', 'GWANGMYEONGSI', 'GWANGYANGSI', 'GYEONGBUK_ALL', 'GYEONGGI_ALL', 'GYEONGJUSI', 'GYEONGNAM_ALL', 'GYEONGNAM_GOSEONGGUN', 'GYEONGSANSI', 'GYERYONGSI', 'GYEYANGGU', 'HADONGGUN', 'HAENAMGUN', 'HAEUNDAEGU', 'HAMANGUN', 'HAMPYEONGGUN', 'HAMYANGGUN', 'HANAMSI', 'HAPCHEONGUN', 'HOENGSEONGGUN', 'HONGCHEONGUN', 'HWACHEONGUN', 'HWASEONGSI', 'HWASUNGUN', 'ICHEONSI', 'IKSANSI', 'IMSIL', 'INCHEON_JUNGGU', 'INCHOEN_ALL', 'INJEGUN', 'JANGHEUNG', 'JANGSEONG', 'JANGSU', 'JECHEONSI', 'JEJU_JEJUSI', 'JEJU_SEOGWIPOSI', 'JEONBUK_ALL', 'JEONGEUP', 'JEONGSEONGUN', 'JEONJU_DEOKJINGU', 'JEONJU_WANSANGU', 'JEONNAM_ALL', 'JINAN', 'JINCHEONGUN', 'JINDOGUN', 'JINJUSI', 'JONGNOGU', 'JUNGGU', 'JUNGRANGGU', 'MAPOGU', 'MICHUHOLGU', 'MILYANGSI', 'MOKPOSI', 'MUANGUN', 'MUJUGUN', 'MUNGYEONGSI', 'NAJUSI', 'NAMDONGGU', 'NAMGU', 'NAMHAEGUN', 'NAMWONSI', 'NAMYANGJUSI', 'NONE', 'NONSANSI', 'NOWONGU', 'OKCHEONGUN', 'ONGJINGUN', 'OSANSI', 'PAJUSI', 'POCHEONSI', 'POHANG_BUKGU', 'POHANG_NAMGU', 'PYEONGCHANGGUN', 'PYEONGTAEKSI', 'SACHEONSI', 'SAHAGU', 'SAMCHEOKSI', 'SANCHEONGGUN', 'SANGJUSI', 'SASANGGU', 'SEJONG', 'SEOCHEONGUN', 'SEOCHOGU', 'SEODAEMUNGU', 'SEOGU', 'SEONGBUKGU', 'SEONGDONGGU', 'SEONGJUGUN', 'SEONGNAM_BUNDANGGU', 'SEONGNAM_JUNGWONGU', 'SEONGNAM_SUJEONGGU', 'SEOSANSI', 'SEOUL_ALL', 'SHINANGUN', 'SIHEUNGSI', 'SOKCHOSI', 'SONGPAGU', 'SUNCHEON', 'SUNCHEONSI', 'SUWON_GWONSEONGU', 'SUWON_JANGANGU', 'SUWON_PALDALGU', 'SUWON_YEONGTONGGU', 'SUYEONGGU', 'TAEAN', 'TAEBAEKSI', 'TONGYEONGSI', 'UIJEONGBUSI', 'UIREONGGUN', 'UISEONGGUN', 'UIWANGSI', 'ULJINGUN', 'ULJUGUN', 'ULLEUNGGUN', 'ULSAN_ALL', 'ULSAN_BUKGU', 'ULSAN_DONGGU', 'ULSAN_JUNGGU', 'ULSAN_NAMGU', 'WANDO', 'WANJU', 'WONJU', 'YANGCHEONGU', 'YANGGUGUN', 'YANGJUSI', 'YANGPYEONGGUN', 'YANGSAN', 'YANGYANGGUN', 'YECHEONGUN', 'YEOJUSI', 'YEONCHEONGUN', 'YEONGAMGUN', 'YEONGCHEONSI', 'YEONGDEOKGUN', 'YEONGDEUNGPOGU', 'YEONGDOGU', 'YEONGDONGGUN', 'YEONGGWANGGUN', 'YEONGJUSI', 'YEONGWOLGUN', 'YEONGYANGGUN', 'YEONJEGU', 'YEONSUGU', 'YEOSUSI', 'YESANGUN', 'YONGIN_CHEOINGU', 'YONGIN_GIHEUNGGU', 'YONGIN_SUJIGU', 'YONGSANGU') NOT NULL,
    `basic_region`      ENUM ('BUSAN', 'CHUNGBUK', 'CHUNGNAM', 'DAEGU', 'DAEJEON', 'GANGWON', 'GWANGJU', 'GYEONGBUK', 'GYEONGGI', 'GYEONGNAM', 'INCHEON', 'JEJU', 'JEONBUK', 'JEONNAM', 'NONE', 'SEJONG', 'SEOUL', 'ULSAN') NOT NULL,
    `birth_date`        DATE NOT NULL,
    `gender`            ENUM ('ALL', 'FEMALE', 'MALE') NOT NULL,
    `match_type`        ENUM ('ALL', 'OFFLINE', 'ONLINE') NULL,
    `member_id`         CHAR(13) NOT NULL,
    `additional_area`   ENUM ('ANDONGSI', 'ANSAN_DANWONGU', 'ANSAN_SANGROKGU', 'ANSEONGSI', 'ANYANG_DONGANGU', 'ANYANG_MANANGU', 'ASANSI', 'BOEUNGUN', 'BONGHWAGUN', 'BORYEONGSI', 'BOSEONGGUN', 'BUAN', 'BUCHEONSI', 'BUKGU', 'BUPYEONGGU', 'BUSANJINGU', 'BUSAN_ALL', 'BUSAN_DONGGU', 'BUSAN_GANGSEOGU', 'BUSAN_JUNGGU', 'BUSAN_SEOGU', 'BUYEO', 'CHANGWON_JINHAEGU', 'CHANGWON_MASANHAPPOGU', 'CHANGWON_MASANHOEWONGU', 'CHANGWON_SEONGSANGU', 'CHANGWON_UICHANGGU', 'CHANGYEONGGUN', 'CHEONAN_SEOBUKGU', 'CHEONGDOGUN', 'CHEONGJU_CHEONGWONGU', 'CHEONGJU_HEUNGDEOKGU', 'CHEONGJU_SANGDANGGU', 'CHEONGJU_SEOWONGU', 'CHEONGSONGGUN', 'CHEONGYANG', 'CHEORWONGUN', 'CHILGOKGUN', 'CHUNCHEONSI', 'CHUNGBUK_ALL', 'CHUNGJUSI', 'CHUNGNAM_ALL', 'DAEGU_ALL', 'DAEGU_BUKGU', 'DAEGU_DALSEOGU', 'DAEGU_DALSEONGGUN', 'DAEGU_DONGGU', 'DAEGU_JUNGGU', 'DAEGU_NAMGU', 'DAEGU_SEOGU', 'DAEGU_SUSEONGGU', 'DAEJEON_ALL', 'DAEJEON_DAEDOKGU', 'DAEJEON_DONGGU', 'DAEJEON_JUNGGU', 'DAEJEON_SEOGU', 'DAEJEON_YUSEONGGU', 'DAMYANGGUN', 'DANGJINSI', 'DANYANGGUN', 'DOBONGGU', 'DONGDAEMUNGU', 'DONGDUCHEONSI', 'DONGGU', 'DONGHAESI', 'DONGJAKGU', 'DONGNAEGU', 'EUMSEONGGUN', 'EUNPYEONGGU', 'GANGBUKGU', 'GANGDONGGU', 'GANGHWAGUN', 'GANGJINGUN', 'GANGNAMGU', 'GANGNEUNGSI', 'GANGSEOGU', 'GANGWON_ALL', 'GANGWON_GOSEONGGUN', 'GAPYEONGGUN', 'GEOCHANGGUN', 'GEOJESI', 'GEUMCHEONGU', 'GEUMJEONGGU', 'GEUMSANGUN', 'GIJANGGUN', 'GIMCHEONSI', 'GIMHAESI', 'GIMJESI', 'GIMPOSI', 'GOCHANGGUN', 'GOHEUNGGUN', 'GOKSEONGGUN', 'GONGJUSI', 'GORYEONGGUN', 'GOYANG_DEOKYANGGU', 'GOYANG_ILSANDONGGU', 'GOYANG_ILSANSEOGU', 'GUAESANGUN', 'GUMISI', 'GUNPOSI', 'GUNSAN', 'GUNWEEGUN', 'GURISI', 'GUROGU', 'GURYEOGUN', 'GWACHEONSI', 'GWANAKGU', 'GWANGJINGU', 'GWANGJUSI', 'GWANGJU_ALL', 'GWANGJU_BUKGU', 'GWANGJU_DONGGU', 'GWANGJU_GWANGSANGU', 'GWANGJU_NAMGU', 'GWANGJU_SEOGU', 'GWANGMYEONGSI', 'GWANGYANGSI', 'GYEONGBUK_ALL', 'GYEONGGI_ALL', 'GYEONGJUSI', 'GYEONGNAM_ALL', 'GYEONGNAM_GOSEONGGUN', 'GYEONGSANSI', 'GYERYONGSI', 'GYEYANGGU', 'HADONGGUN', 'HAENAMGUN', 'HAEUNDAEGU', 'HAMANGUN', 'HAMPYEONGGUN', 'HAMYANGGUN', 'HANAMSI', 'HAPCHEONGUN', 'HOENGSEONGGUN', 'HONGCHEONGUN', 'HWACHEONGUN', 'HWASEONGSI', 'HWASUNGUN', 'ICHEONSI', 'IKSANSI', 'IMSIL', 'INCHEON_JUNGGU', 'INCHOEN_ALL', 'INJEGUN', 'JANGHEUNG', 'JANGSEONG', 'JANGSU', 'JECHEONSI', 'JEJU_JEJUSI', 'JEJU_SEOGWIPOSI', 'JEONBUK_ALL', 'JEONGEUP', 'JEONGSEONGUN', 'JEONJU_DEOKJINGU', 'JEONJU_WANSANGU', 'JEONNAM_ALL', 'JINAN', 'JINCHEONGUN', 'JINDOGUN', 'JINJUSI', 'JONGNOGU', 'JUNGGU', 'JUNGRANGGU', 'MAPOGU', 'MICHUHOLGU', 'MILYANGSI', 'MOKPOSI', 'MUANGUN', 'MUJUGUN', 'MUNGYEONGSI', 'NAJUSI', 'NAMDONGGU', 'NAMGU', 'NAMHAEGUN', 'NAMWONSI', 'NAMYANGJUSI', 'NONE', 'NONSANSI', 'NOWONGU', 'OKCHEONGUN', 'ONGJINGUN', 'OSANSI', 'PAJUSI', 'POCHEONSI', 'POHANG_BUKGU', 'POHANG_NAMGU', 'PYEONGCHANGGUN', 'PYEONGTAEKSI', 'SACHEONSI', 'SAHAGU', 'SAMCHEOKSI', 'SANCHEONGGUN', 'SANGJUSI', 'SASANGGU', 'SEJONG', 'SEOCHEONGUN', 'SEOCHOGU', 'SEODAEMUNGU', 'SEOGU', 'SEONGBUKGU', 'SEONGDONGGU', 'SEONGJUGUN', 'SEONGNAM_BUNDANGGU', 'SEONGNAM_JUNGWONGU', 'SEONGNAM_SUJEONGGU', 'SEOSANSI', 'SEOUL_ALL', 'SHINANGUN', 'SIHEUNGSI', 'SOKCHOSI', 'SONGPAGU', 'SUNCHEON', 'SUNCHEONSI', 'SUWON_GWONSEONGU', 'SUWON_JANGANGU', 'SUWON_PALDALGU', 'SUWON_YEONGTONGGU', 'SUYEONGGU', 'TAEAN', 'TAEBAEKSI', 'TONGYEONGSI', 'UIJEONGBUSI', 'UIREONGGUN', 'UISEONGGUN', 'UIWANGSI', 'ULJINGUN', 'ULJUGUN', 'ULLEUNGGUN', 'ULSAN_ALL', 'ULSAN_BUKGU', 'ULSAN_DONGGU', 'ULSAN_JUNGGU', 'ULSAN_NAMGU', 'WANDO', 'WANJU', 'WONJU', 'YANGCHEONGU', 'YANGGUGUN', 'YANGJUSI', 'YANGPYEONGGUN', 'YANGSAN', 'YANGYANGGUN', 'YECHEONGUN', 'YEOJUSI', 'YEONCHEONGUN', 'YEONGAMGUN', 'YEONGCHEONSI', 'YEONGDEOKGUN', 'YEONGDEUNGPOGU', 'YEONGDOGU', 'YEONGDONGGUN', 'YEONGGWANGGUN', 'YEONGJUSI', 'YEONGWOLGUN', 'YEONGYANGGUN', 'YEONJEGU', 'YEONSUGU', 'YEOSUSI', 'YESANGUN', 'YONGIN_CHEOINGU', 'YONGIN_GIHEUNGGU', 'YONGIN_SUJIGU', 'YONGSANGU') NOT NULL,
    `additional_region` ENUM ('BUSAN', 'CHUNGBUK', 'CHUNGNAM', 'DAEGU', 'DAEJEON', 'GANGWON', 'GWANGJU', 'GYEONGBUK', 'GYEONGGI', 'GYEONGNAM', 'INCHEON', 'JEJU', 'JEONBUK', 'JEONNAM', 'NONE', 'SEJONG', 'SEOUL', 'ULSAN') NOT NULL,
    constraint UKtvptoe1hqh8t09s7upisuif0
        unique (member_id),
    constraint FK_participant_member
        foreign key (member_id) references member (member_id)
            on delete cascade
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `researcher` (
    `researcher_id` CHAR(13) NOT NULL PRIMARY KEY,
    `email_verified` BIT NOT NULL,
    `lab_info` VARCHAR(100) NULL,
    `major` VARCHAR(10) NOT NULL,
    `univ_email` VARCHAR(100) NOT NULL,
    `univ_name` VARCHAR(100) NOT NULL,
    `member_id` CHAR(13) NOT NULL UNIQUE,
    CONSTRAINT FK_researcher_member FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `target_group` (
    `target_group_id` CHAR(13) NOT NULL PRIMARY KEY,
    `end_age` INT NULL,
    `gender_type` ENUM ('ALL', 'FEMALE', 'MALE') NOT NULL,
    `other_condition` VARCHAR(300) NULL,
    `start_age` INT NULL,
    CONSTRAINT CHK_target_group_age CHECK (start_age >= 0 AND end_age >= start_age)
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `verification` (
    `verification_id` CHAR(13) NOT NULL PRIMARY KEY,
    `created_at` DATETIME(6) NOT NULL,
    `expires_at` DATETIME(6) NOT NULL,
    `status` ENUM ('HOLD', 'VERIFIED') NOT NULL,
    `univ_email` VARCHAR(255) NOT NULL,
    `updated_at` DATETIME(6) NOT NULL,
    `verification_code` VARCHAR(6) NOT NULL,
    CONSTRAINT UK8nj313m4fya5vr4emod227psv UNIQUE (univ_email),
    CONSTRAINT UKh1ganastgcw00w0sl7wwib132 UNIQUE (verification_code)
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `apply_method` (
    `apply_method_id` CHAR(13) NOT NULL PRIMARY KEY,
    `content` VARCHAR(200) NOT NULL,
    `form_url` VARCHAR(100) NULL,
    `phone_num` VARCHAR(50) NULL,
    CONSTRAINT CHK_apply_method_content CHECK (content IS NOT NULL AND OCTET_LENGTH(content) > 0)
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `experiment_post` (
    `experiment_post_id` CHAR(13) NOT NULL PRIMARY KEY,
    `alarm_agree`        BIT NOT NULL,
    `area`               ENUM ('ANDONGSI', 'ANSAN_DANWONGU', 'ANSAN_SANGROKGU', 'ANSEONGSI', 'ANYANG_DONGANGU', 'ANYANG_MANANGU', 'ASANSI', 'BOEUNGUN', 'BONGHWAGUN', 'BORYEONGSI', 'BOSEONGGUN', 'BUAN', 'BUCHEONSI', 'BUKGU', 'BUPYEONGGU', 'BUSANJINGU', 'BUSAN_ALL', 'BUSAN_DONGGU', 'BUSAN_GANGSEOGU', 'BUSAN_JUNGGU', 'BUSAN_SEOGU', 'BUYEO', 'CHANGWON_JINHAEGU', 'CHANGWON_MASANHAPPOGU', 'CHANGWON_MASANHOEWONGU', 'CHANGWON_SEONGSANGU', 'CHANGWON_UICHANGGU', 'CHANGYEONGGUN', 'CHEONAN_SEOBUKGU', 'CHEONGDOGUN', 'CHEONGJU_CHEONGWONGU', 'CHEONGJU_HEUNGDEOKGU', 'CHEONGJU_SANGDANGGU', 'CHEONGJU_SEOWONGU', 'CHEONGSONGGUN', 'CHEONGYANG', 'CHEORWONGUN', 'CHILGOKGUN', 'CHUNCHEONSI', 'CHUNGBUK_ALL', 'CHUNGJUSI', 'CHUNGNAM_ALL', 'DAEGU_ALL', 'DAEGU_BUKGU', 'DAEGU_DALSEOGU', 'DAEGU_DALSEONGGUN', 'DAEGU_DONGGU', 'DAEGU_JUNGGU', 'DAEGU_NAMGU', 'DAEGU_SEOGU', 'DAEGU_SUSEONGGU', 'DAEJEON_ALL', 'DAEJEON_DAEDOKGU', 'DAEJEON_DONGGU', 'DAEJEON_JUNGGU', 'DAEJEON_SEOGU', 'DAEJEON_YUSEONGGU', 'DAMYANGGUN', 'DANGJINSI', 'DANYANGGUN', 'DOBONGGU', 'DONGDAEMUNGU', 'DONGDUCHEONSI', 'DONGGU', 'DONGHAESI', 'DONGJAKGU', 'DONGNAEGU', 'EUMSEONGGUN', 'EUNPYEONGGU', 'GANGBUKGU', 'GANGDONGGU', 'GANGHWAGUN', 'GANGJINGUN', 'GANGNAMGU', 'GANGNEUNGSI', 'GANGSEOGU', 'GANGWON_ALL', 'GANGWON_GOSEONGGUN', 'GAPYEONGGUN', 'GEOCHANGGUN', 'GEOJESI', 'GEUMCHEONGU', 'GEUMJEONGGU', 'GEUMSANGUN', 'GIJANGGUN', 'GIMCHEONSI', 'GIMHAESI', 'GIMJESI', 'GIMPOSI', 'GOCHANGGUN', 'GOHEUNGGUN', 'GOKSEONGGUN', 'GONGJUSI', 'GORYEONGGUN', 'GOYANG_DEOKYANGGU', 'GOYANG_ILSANDONGGU', 'GOYANG_ILSANSEOGU', 'GUAESANGUN', 'GUMISI', 'GUNPOSI', 'GUNSAN', 'GUNWEEGUN', 'GURISI', 'GUROGU', 'GURYEOGUN', 'GWACHEONSI', 'GWANAKGU', 'GWANGJINGU', 'GWANGJUSI', 'GWANGJU_ALL', 'GWANGJU_BUKGU', 'GWANGJU_DONGGU', 'GWANGJU_GWANGSANGU', 'GWANGJU_NAMGU', 'GWANGJU_SEOGU', 'GWANGMYEONGSI', 'GWANGYANGSI', 'GYEONGBUK_ALL', 'GYEONGGI_ALL', 'GYEONGJUSI', 'GYEONGNAM_ALL', 'GYEONGNAM_GOSEONGGUN', 'GYEONGSANSI', 'GYERYONGSI', 'GYEYANGGU', 'HADONGGUN', 'HAENAMGUN', 'HAEUNDAEGU', 'HAMANGUN', 'HAMPYEONGGUN', 'HAMYANGGUN', 'HANAMSI', 'HAPCHEONGUN', 'HOENGSEONGGUN', 'HONGCHEONGUN', 'HWACHEONGUN', 'HWASEONGSI', 'HWASUNGUN', 'ICHEONSI', 'IKSANSI', 'IMSIL', 'INCHEON_JUNGGU', 'INCHOEN_ALL', 'INJEGUN', 'JANGHEUNG', 'JANGSEONG', 'JANGSU', 'JECHEONSI', 'JEJU_JEJUSI', 'JEJU_SEOGWIPOSI', 'JEONBUK_ALL', 'JEONGEUP', 'JEONGSEONGUN', 'JEONJU_DEOKJINGU', 'JEONJU_WANSANGU', 'JEONNAM_ALL', 'JINAN', 'JINCHEONGUN', 'JINDOGUN', 'JINJUSI', 'JONGNOGU', 'JUNGGU', 'JUNGRANGGU', 'MAPOGU', 'MICHUHOLGU', 'MILYANGSI', 'MOKPOSI', 'MUANGUN', 'MUJUGUN', 'MUNGYEONGSI', 'NAJUSI', 'NAMDONGGU', 'NAMGU', 'NAMHAEGUN', 'NAMWONSI', 'NAMYANGJUSI', 'NONE', 'NONSANSI', 'NOWONGU', 'OKCHEONGUN', 'ONGJINGUN', 'OSANSI', 'PAJUSI', 'POCHEONSI', 'POHANG_BUKGU', 'POHANG_NAMGU', 'PYEONGCHANGGUN', 'PYEONGTAEKSI', 'SACHEONSI', 'SAHAGU', 'SAMCHEOKSI', 'SANCHEONGGUN', 'SANGJUSI', 'SASANGGU', 'SEJONG', 'SEOCHEONGUN', 'SEOCHOGU', 'SEODAEMUNGU', 'SEOGU', 'SEONGBUKGU', 'SEONGDONGGU', 'SEONGJUGUN', 'SEONGNAM_BUNDANGGU', 'SEONGNAM_JUNGWONGU', 'SEONGNAM_SUJEONGGU', 'SEOSANSI', 'SEOUL_ALL', 'SHINANGUN', 'SIHEUNGSI', 'SOKCHOSI', 'SONGPAGU', 'SUNCHEON', 'SUNCHEONSI', 'SUWON_GWONSEONGU', 'SUWON_JANGANGU', 'SUWON_PALDALGU', 'SUWON_YEONGTONGGU', 'SUYEONGGU', 'TAEAN', 'TAEBAEKSI', 'TONGYEONGSI', 'UIJEONGBUSI', 'UIREONGGUN', 'UISEONGGUN', 'UIWANGSI', 'ULJINGUN', 'ULJUGUN', 'ULLEUNGGUN', 'ULSAN_ALL', 'ULSAN_BUKGU', 'ULSAN_DONGGU', 'ULSAN_JUNGGU', 'ULSAN_NAMGU', 'WANDO', 'WANJU', 'WONJU', 'YANGCHEONGU', 'YANGGUGUN', 'YANGJUSI', 'YANGPYEONGGUN', 'YANGSAN', 'YANGYANGGUN', 'YECHEONGUN', 'YEOJUSI', 'YEONCHEONGUN', 'YEONGAMGUN', 'YEONGCHEONSI', 'YEONGDEOKGUN', 'YEONGDEUNGPOGU', 'YEONGDOGU', 'YEONGDONGGUN', 'YEONGGWANGGUN', 'YEONGJUSI', 'YEONGWOLGUN', 'YEONGYANGGUN', 'YEONJEGU', 'YEONSUGU', 'YEOSUSI', 'YESANGUN', 'YONGIN_CHEOINGU', 'YONGIN_GIHEUNGGU', 'YONGIN_SUJIGU', 'YONGSANGU') NULL,
    `content`            VARCHAR(5000) NOT NULL,
    `count`              INT NOT NULL,
    `created_at`         DATETIME(6) NOT NULL,
    `detailed_address`   VARCHAR(70) NULL,
    `end_date`           DATE NULL,
    `lead_researcher`    VARCHAR(150) NOT NULL,
    `match_type`         ENUM ('ALL', 'OFFLINE', 'ONLINE') NOT NULL,
    `recruit_status`     BIT NOT NULL,
    `region`             ENUM ('BUSAN', 'CHUNGBUK', 'CHUNGNAM', 'DAEGU', 'DAEJEON', 'GANGWON', 'GWANGJU', 'GYEONGBUK', 'GYEONGGI', 'GYEONGNAM', 'INCHEON', 'JEJU', 'JEONBUK', 'JEONNAM', 'NONE', 'SEJONG', 'SEOUL', 'ULSAN') NULL,
    `reward`             VARCHAR(170) NOT NULL,
    `start_date`         DATE NULL,
    `time_required`      ENUM ('ABOUT_1H', 'ABOUT_1H30M', 'ABOUT_2H', 'ABOUT_2H30M', 'ABOUT_30M', 'ABOUT_3H', 'ABOUT_3H30M', 'ABOUT_4H', 'LESS_30M') NULL,
    `title`              VARCHAR(70) NOT NULL,
    `place`              VARCHAR(100) NULL,
    `updated_at`         DATETIME(6) NOT NULL,
    `views`              INT NULL,
    `apply_method_id`    CHAR(13) NULL,
    `member_id`          CHAR(13) NULL,
    `target_group_id`    CHAR(13) NULL,
    constraint UK3w7710ejwtguc97uo8q5oxr1c
        unique (apply_method_id),
    constraint UKqh8n41363sk7cv8cqomhuc28o
        unique (target_group_id),
    constraint FK_experiment_post_apply_method
        foreign key (apply_method_id) references apply_method (apply_method_id)
            on delete cascade,
    constraint FK_experiment_post_member
        foreign key (member_id) references member (member_id)
            on delete cascade,
    constraint FK_experiment_post_target_group
        foreign key (target_group_id) references target_group (target_group_id)
            on delete cascade
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `experiment_image` (
    `experiment_image_id` CHAR(13) NOT NULL PRIMARY KEY,
    `image_url` VARCHAR(255) NOT NULL,
    `experiment_post_id` CHAR(13) NULL,
    CONSTRAINT FK_experiment_image_experiment_post FOREIGN KEY (experiment_post_id) REFERENCES experiment_post (experiment_post_id) ON DELETE CASCADE,
    CONSTRAINT CHK_experiment_image_url CHECK (image_url IS NOT NULL AND OCTET_LENGTH(image_url) > 0)
) COLLATE = utf8mb4_unicode_ci;
