name: Development Server CI/CD

on:
  push:
    branches: [ "dev" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: ✔️ checkout
        uses: actions/checkout@v3

      - name: ✔️ set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ✔️ create application.yml
        run: |
          cd ./infrastructure/src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.DEV_YML }}" >> ./application-dev.yml
        shell: bash

      - name: ✔️ give executive authority to gradlew
        run: chmod +x gradlew

      - name: ✔️ build gradlew
        run: ./gradlew clean build -x test --stacktrace

      - name: ✔️ build docker image and push to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --build-arg SPRING_PROFILES_ACTIVE=dev -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:dev

      - name: ✔️ send deploy-dev.sh to EC2 development server
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.DEV_WAS_HOST }}
          key: ${{ secrets.DEV_WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          source: "./scripts/deploy-dev.sh"
          target: "/home/ubuntu/"

      - name: ✔️ send docker-compose-dev.yml to EC2 development server
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.DEV_WAS_HOST }}
          key: ${{ secrets.DEV_WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          source: "./docker-compose-dev.yml"
          target: "/home/ubuntu/"

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: ✔️ checkout
        uses: actions/checkout@v3

      - name: ✔️ pull docker image from docker hub and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.DEV_WAS_HOST }}
          key: ${{ secrets.DEV_WAS_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:dev
            chmod 777 ./scripts/deploy-dev.sh
            cp ./scripts/deploy-dev.sh ./deploy-dev.sh
            ./deploy-dev.sh
            docker image prune -f
